apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-gke
  labels:
    app: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 3
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: naveenjain94/order_service:v2
        ports:
        - containerPort: 7000
        env:
        - name: JAEGER_HOST
          valueFrom:
            configMapKeyRef:
              name: jaeger-config
              key: JAEGER_HOST
        - name: JAEGER_PORT
          valueFrom:
            configMapKeyRef:
              name: jaeger-config
              key: JAEGER_PORT
