apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-service-gke
  labels:
    app: order-management-service
spec:
  selector:
    matchLabels:
      app: order-management-service
  replicas: 3
  template:
    metadata:
      labels:
        app: order-management-service
    spec:
      containers:
      - name: order-management-service
        image: naveenjain94/order_management_service:v2
        ports:
        - containerPort: 8000
        env:
        - name: USER_URI
          valueFrom:
            configMapKeyRef:
              name: order-management-config
              key: USER_URI
        - name: ORDER_URI
          valueFrom:
            configMapKeyRef:
              name: order-management-config
              key: ORDER_URI
        - name: JAEGER_HOST
          valueFrom:
            configMapKeyRef:
              name: jaeger-config
              key: JAEGER_HOST
        - name: JAEGER_PORT
          valueFrom:
            configMapKeyRef:
              name: jaeger-config
              key: JAEGER_PORT
