apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-gke
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 3
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: naveenjain94/userservice
        ports:
        - containerPort: 6000
